image: docker:stable

services:
    - docker:stable-dind

.build_image_template: &build_image_definition
    script:
    - docker build -t "${CI_REGISTRY_IMAGE}:${VERSION}" "${IMAGE_PATH}"
    except:
    - master

.build_and_push_image_template: &build_image_push_definition
    script:
    - docker info
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"
    - docker build -t "${CI_REGISTRY_IMAGE}:${VERSION}" "${IMAGE_PATH}"
    - docker tag "${CI_REGISTRY_IMAGE}:${VERSION}" "${CI_REGISTRY_IMAGE}:${VERSION}";
    - docker push "${CI_REGISTRY_IMAGE}"
    only:
    - master

############################

# BUILD and PUSH
#3.1
v3.1-cuda9.0-u16-gl_push:
    variables:
        VERSION: "3.1-gl-devel-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "3.1/ubuntu1604/cuda9.0/devel-gl"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda9.0-u16_push:
    variables:
        VERSION: "3.1-devel-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "3.1/ubuntu1604/cuda9.0/devel"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda9.0-u16-ros_push:
    variables:
        VERSION: "3.1-ros-devel-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "3.1/ubuntu1604/cuda9.0/devel-ros"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.0-u16-gl_push:
    variables:
        VERSION: "3.1-gl-devel-cuda10.0-ubuntu16.04"
        IMAGE_PATH: "3.1/ubuntu1604/cuda10.0/devel-gl"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.0-u16_push:
    variables:
        VERSION: "3.1-devel-cuda10.0-ubuntu16.04"
        IMAGE_PATH: "3.1/ubuntu1604/cuda10.0/devel"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.2-u16-gl_push:
    variables:
        VERSION: "3.1-gl-devel-cuda10.2-ubuntu16.04"
        IMAGE_PATH: "3.1/ubuntu1604/cuda10.2/devel-gl"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.2-u16_push:
    variables:
        VERSION: "3.1-devel-cuda10.2-ubuntu16.04"
        IMAGE_PATH: "3.1/ubuntu1604/cuda10.2/devel"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.0-u18-gl_push:
    variables:
        VERSION: "3.1-gl-devel-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "3.1/ubuntu1804/cuda10.0/devel-gl"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.0-u18_push:
    variables:
        VERSION: "3.1-devel-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "3.1/ubuntu1804/cuda10.0/devel"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.2-u18-gl_push:
    variables:
        VERSION: "3.1-gl-devel-cuda10.2-ubuntu18.04"
        IMAGE_PATH: "3.1/ubuntu1804/cuda10.2/devel-gl"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.2-u18_push:
    variables:
        VERSION: "3.1-devel-cuda10.2-ubuntu18.04"
        IMAGE_PATH: "3.1/ubuntu1804/cuda10.2/devel"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.0-u18-ros_push:
    variables:
        VERSION: "3.1-ros-devel-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "3.1/ubuntu1804/cuda10.0/devel-ros"
    when: manual
    <<: *build_image_push_definition
#
v3.1-cuda9.0-u16-run_push:
    variables:
        VERSION: "3.1-runtime-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "3.1/ubuntu1604/cuda9.0/runtime"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.0-u16-run_push:
    variables:
        VERSION: "3.1-runtime-cuda10.0-ubuntu16.04"
        IMAGE_PATH: "3.1/ubuntu1604/cuda10.0/runtime"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.2-u16-run_push:
    variables:
        VERSION: "3.1-runtime-cuda10.2-ubuntu16.04"
        IMAGE_PATH: "3.1/ubuntu1604/cuda10.2/runtime"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.0-u18-run_push:
    variables:
        VERSION: "3.1-runtime-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "3.1/ubuntu1804/cuda10.0/runtime"
    when: manual
    <<: *build_image_push_definition

v3.1-cuda10.2-u18-run_push:
    variables:
        VERSION: "3.1-runtime-cuda10.2-ubuntu18.04"
        IMAGE_PATH: "3.1/ubuntu1804/cuda10.2/runtime"
    when: manual
    <<: *build_image_push_definition


##### 3.0
v3.0-cuda9.0-u16-gl_push:
    variables:
        VERSION: "3.0-gl-devel-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "3.0/ubuntu1604/cuda9.0/devel-gl"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda9.0-u16_push:
    variables:
        VERSION: "3.0-devel-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "3.0/ubuntu1604/cuda9.0/devel"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda9.0-u16-ros_push:
    variables:
        VERSION: "3.0-ros-devel-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "3.0/ubuntu1604/cuda9.0/devel-ros"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.0-u16-gl_push:
    variables:
        VERSION: "3.0-gl-devel-cuda10.0-ubuntu16.04"
        IMAGE_PATH: "3.0/ubuntu1604/cuda10.0/devel-gl"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.0-u16_push:
    variables:
        VERSION: "3.0-devel-cuda10.0-ubuntu16.04"
        IMAGE_PATH: "3.0/ubuntu1604/cuda10.0/devel"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.2-u16-gl_push:
    variables:
        VERSION: "3.0-gl-devel-cuda10.2-ubuntu16.04"
        IMAGE_PATH: "3.0/ubuntu1604/cuda10.2/devel-gl"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.2-u16_push:
    variables:
        VERSION: "3.0-devel-cuda10.2-ubuntu16.04"
        IMAGE_PATH: "3.0/ubuntu1604/cuda10.2/devel"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.0-u18-gl_push:
    variables:
        VERSION: "3.0-gl-devel-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "3.0/ubuntu1804/cuda10.0/devel-gl"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.0-u18_push:
    variables:
        VERSION: "3.0-devel-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "3.0/ubuntu1804/cuda10.0/devel"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.2-u18-gl_push:
    variables:
        VERSION: "3.0-gl-devel-cuda10.2-ubuntu18.04"
        IMAGE_PATH: "3.0/ubuntu1804/cuda10.2/devel-gl"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.2-u18_push:
    variables:
        VERSION: "3.0-devel-cuda10.2-ubuntu18.04"
        IMAGE_PATH: "3.0/ubuntu1804/cuda10.2/devel"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.0-u18-ros_push:
    variables:
        VERSION: "3.0-ros-devel-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "3.0/ubuntu1804/cuda10.0/devel-ros"
    when: manual
    <<: *build_image_push_definition
#
v3.0-cuda9.0-u16-run_push:
    variables:
        VERSION: "3.0-runtime-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "3.0/ubuntu1604/cuda9.0/runtime"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.0-u16-run_push:
    variables:
        VERSION: "3.0-runtime-cuda10.0-ubuntu16.04"
        IMAGE_PATH: "3.0/ubuntu1604/cuda10.0/runtime"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.2-u16-run_push:
    variables:
        VERSION: "3.0-runtime-cuda10.2-ubuntu16.04"
        IMAGE_PATH: "3.0/ubuntu1604/cuda10.2/runtime"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.0-u18-run_push:
    variables:
        VERSION: "3.0-runtime-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "3.0/ubuntu1804/cuda10.0/runtime"
    when: manual
    <<: *build_image_push_definition

v3.0-cuda10.2-u18-run_push:
    variables:
        VERSION: "3.0-runtime-cuda10.2-ubuntu18.04"
        IMAGE_PATH: "3.0/ubuntu1804/cuda10.2/runtime"
    when: manual
    <<: *build_image_push_definition


#2.8
v2.8-cuda9.0-u16-gl_push:
    variables:
        VERSION: "2.8-gl-devel-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "2.8/ubuntu1604/cuda9.0/devel-gl"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda9.0-u16_push:
    variables:
        VERSION: "2.8-devel-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "2.8/ubuntu1604/cuda9.0/devel"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda9.0-u16-ros_push:
    variables:
        VERSION: "2.8-ros-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "2.8/ubuntu1604/cuda9.0/ros"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.0-u16-gl_push:
    variables:
        VERSION: "2.8-gl-devel-cuda10.0-ubuntu16.04"
        IMAGE_PATH: "2.8/ubuntu1604/cuda10.0/devel-gl"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.0-u16_push:
    variables:
        VERSION: "2.8-devel-cuda10.0-ubuntu16.04"
        IMAGE_PATH: "2.8/ubuntu1604/cuda10.0/devel"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.2-u16-gl_push:
    variables:
        VERSION: "2.8-gl-devel-cuda10.2-ubuntu16.04"
        IMAGE_PATH: "2.8/ubuntu1604/cuda10.2/devel-gl"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.2-u16_push:
    variables:
        VERSION: "2.8-devel-cuda10.2-ubuntu16.04"
        IMAGE_PATH: "2.8/ubuntu1604/cuda10.2/devel"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.0-u18-gl_push:
    variables:
        VERSION: "2.8-gl-devel-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "2.8/ubuntu1804/cuda10.0/devel-gl"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.0-u18_push:
    variables:
        VERSION: "2.8-devel-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "2.8/ubuntu1804/cuda10.0/devel"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.2-u18-gl_push:
    variables:
        VERSION: "2.8-gl-devel-cuda10.2-ubuntu18.04"
        IMAGE_PATH: "2.8/ubuntu1804/cuda10.2/devel-gl"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.2-u18_push:
    variables:
        VERSION: "2.8-devel-cuda10.2-ubuntu18.04"
        IMAGE_PATH: "2.8/ubuntu1804/cuda10.2/devel"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.0-u18-ros_push:
    variables:
        VERSION: "2.8-ros-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "2.8/ubuntu1804/cuda10.0/ros"
    when: manual
    <<: *build_image_push_definition
#
v2.8-cuda9.0-u16-run_push:
    variables:
        VERSION: "2.8-runtime-cuda9.0-ubuntu16.04"
        IMAGE_PATH: "2.8/ubuntu1604/cuda9.0/runtime"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.0-u16-run_push:
    variables:
        VERSION: "2.8-runtime-cuda10.0-ubuntu16.04"
        IMAGE_PATH: "2.8/ubuntu1604/cuda10.0/runtime"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.2-u16-run_push:
    variables:
        VERSION: "2.8-runtime-cuda10.2-ubuntu16.04"
        IMAGE_PATH: "2.8/ubuntu1604/cuda10.2/runtime"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.0-u18-run_push:
    variables:
        VERSION: "2.8-runtime-cuda10.0-ubuntu18.04"
        IMAGE_PATH: "2.8/ubuntu1804/cuda10.0/runtime"
    when: manual
    <<: *build_image_push_definition

v2.8-cuda10.2-u18-run_push:
    variables:
        VERSION: "2.8-runtime-cuda10.2-ubuntu18.04"
        IMAGE_PATH: "2.8/ubuntu1804/cuda10.2/runtime"
    when: manual
    <<: *build_image_push_definition