# Inspired from https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/.gitlab-ci.yml
image: docker:stable

services:
    - docker:stable-dind

.build_image_template: &build_image_definition
    script:
    - docker build -t "${CI_REGISTRY_IMAGE}:${VERSION}" "${IMAGE_PATH}"
    except:
    - master

.build_and_push_image_template: &build_image_push_definition
    script:
    - docker info
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"
    - docker build -t "${CI_REGISTRY_IMAGE}:${VERSION}" "${IMAGE_PATH}"
    - docker tag "${CI_REGISTRY_IMAGE}:${VERSION}" "${CI_REGISTRY_IMAGE}:${VERSION}";
    - docker push "${CI_REGISTRY_IMAGE}"
    only:
    - master

# BUILD
v2.6-cuda9.0-gl:
    variables:
        VERSION: "ubuntu1604-cuda9.0-zed2.6-gl"
        IMAGE_PATH: "2.6/ubuntu1604/cuda9.0/devel-gl"
    <<: *build_image_definition

v2.6-cuda9.0:
    variables:
        VERSION: "ubuntu1604-cuda9.0-zed2.6"
        IMAGE_PATH: "2.6/ubuntu1604/cuda9.0/devel"
    <<: *build_image_definition

v2.6-cuda9.0-ros:
    variables:
        VERSION: "ubuntu1604-cuda9.0-zed2.6-ros"
        IMAGE_PATH: "2.6/ubuntu1604/cuda9.0/ros"
    <<: *build_image_definition

v2.6-cuda9.2:
    variables:
        VERSION: "ubuntu1604-cuda9.2-zed2.6"
        IMAGE_PATH: "2.6/ubuntu1604/cuda9.2/devel"
    <<: *build_image_definition

# BUILD and PUSH
v2.6-cuda9.0-gl_push:
    variables:
        VERSION: "ubuntu1604-cuda9.0-zed2.6-gl"
        IMAGE_PATH: "2.6/ubuntu1604/cuda9.0/devel-gl"
    <<: *build_image_push_definition

v2.6-cuda9.0_push:
    variables:
        VERSION: "ubuntu1604-cuda9.0-zed2.6"
        IMAGE_PATH: "2.6/ubuntu1604/cuda9.0/devel"
    <<: *build_image_push_definition

v2.6-cuda9.0-ros_push:
    variables:
        VERSION: "ubuntu1604-cuda9.0-zed2.6-ros"
        IMAGE_PATH: "2.6/ubuntu1604/cuda9.0/ros"
    <<: *build_image_push_definition

v2.6-cuda9.2_push:
    variables:
        VERSION: "ubuntu1604-cuda9.2-zed2.6"
        IMAGE_PATH: "2.6/ubuntu1604/cuda9.2/devel"
    <<: *build_image_push_definition
